title: <p align="center"> Anuja Gurav </p>
logo: /assets/img/MachineLearningLogo.png
description: Working on Machine Learning related Projects.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
